#!/bin/sh
#
# Pre-commit hook managed by cargo-husky.
# Matches CI: cargo clippy --all-targets --all-features -- -D warnings
#

set -e

echo '+cargo clippy --all-targets --all-features -- -D warnings'
cargo clippy --all-targets --all-features -- -D warnings
echo '+cargo fmt -- --check'
cargo fmt -- --check
